"""
Geometry optimization using RDKit force fields (UFF/MMFF).
"""

from rdkit import Chem
from rdkit.Chem import AllChem, rdDetermineBonds
import numpy as np


class GeometryOptimizer:
    """Optimize molecular geometry using RDKit force fields."""

    def __init__(self, atoms, charge=0):
        """
        Args:
            atoms: List of tuples (element, x, y, z)
            charge: Molecular charge (default 0)
        """
        self.atoms = atoms
        self.charge = charge
        self.mol = None
        self.optimized_atoms = None
        self.success = False
        self.error_message = ""

    def _atoms_to_xyz_block(self):
        """Convert atoms list to XYZ block format for RDKit."""
        lines = [str(len(self.atoms)), "Generated by LOWDIN Translator"]
        for symbol, x, y, z in self.atoms:
            lines.append(f"{symbol} {x:.6f} {y:.6f} {z:.6f}")
        return "\n".join(lines)

    def _mol_from_atoms(self):
        """Create RDKit mol object from atoms list."""
        xyz_block = self._atoms_to_xyz_block()
        raw_mol = Chem.MolFromXYZBlock(xyz_block)

        if raw_mol is None:
            self.error_message = "Failed to parse XYZ data"
            return None

        # Try bond perception strategies in order of preference.
        # DetermineBonds raises ValueError when it can't satisfy the requested
        # charge with neutral-valence bond orders; allowChargedFragments=True
        # lets it place formal charges on atoms instead.
        attempts = [
            {"charge": self.charge, "allowChargedFragments": True},
            {"charge": self.charge, "allowChargedFragments": False},
            {"charge": 0,           "allowChargedFragments": True},
        ]

        for kwargs in attempts:
            try:
                mol = Chem.RWMol(Chem.Mol(raw_mol))
                rdDetermineBonds.DetermineBonds(mol, **kwargs)
                if kwargs["charge"] != self.charge:
                    self.error_message = (
                        f"Warning: could not assign bonds with charge={self.charge}; "
                        "optimizing as neutral molecule"
                    )
                return mol
            except Exception:
                continue

        self.error_message = "Bond perception failed for this molecule"
        return None

    def _extract_coordinates(self, mol):
        """Extract optimized coordinates from RDKit mol."""
        conf = mol.GetConformer()
        atoms = []

        for atom_idx in range(mol.GetNumAtoms()):
            atom = mol.GetAtomWithIdx(atom_idx)
            symbol = atom.GetSymbol()
            pos = conf.GetAtomPosition(atom_idx)
            atoms.append((symbol, pos.x, pos.y, pos.z))

        return atoms

    def optimize_uff(self, max_iters=200):
        """
        Optimize geometry using Universal Force Field (UFF).

        Args:
            max_iters: Maximum optimization iterations

        Returns:
            True if successful, False otherwise
        """
        self.mol = self._mol_from_atoms()
        if self.mol is None:
            return False

        try:
            # Run UFF optimization
            result = AllChem.UFFOptimizeMolecule(self.mol, maxIters=max_iters)

            if result == 0:
                self.success = True
                self.optimized_atoms = self._extract_coordinates(self.mol)
                return True
            else:
                self.error_message = f"Optimization did not converge (code {result})"
                return False

        except Exception as e:
            self.error_message = f"UFF optimization failed: {str(e)}"
            return False

    def optimize_mmff(self, max_iters=200):
        """
        Optimize geometry using Merck Molecular Force Field (MMFF94).

        Args:
            max_iters: Maximum optimization iterations

        Returns:
            True if successful, False otherwise
        """
        self.mol = self._mol_from_atoms()
        if self.mol is None:
            return False

        try:
            # Get MMFF properties
            props = AllChem.MMFFGetMoleculeProperties(self.mol)
            if props is None:
                self.error_message = "MMFF force field not applicable to this molecule"
                return False

            # Run MMFF optimization
            result = AllChem.MMFFOptimizeMolecule(self.mol, maxIters=max_iters)

            if result == 0:
                self.success = True
                self.optimized_atoms = self._extract_coordinates(self.mol)
                return True
            else:
                self.error_message = f"Optimization did not converge (code {result})"
                return False

        except Exception as e:
            self.error_message = f"MMFF optimization failed: {str(e)}"
            return False

    def optimize(self, method="UFF", max_iters=200):
        """
        Optimize geometry with specified force field.

        Args:
            method: "UFF" or "MMFF" (default "UFF")
            max_iters: Maximum optimization iterations

        Returns:
            Optimized atoms list [(symbol, x, y, z), ...] or None if failed
        """
        if method.upper() == "MMFF":
            success = self.optimize_mmff(max_iters)
        else:
            success = self.optimize_uff(max_iters)

        if success:
            return self.optimized_atoms
        else:
            return None

    def get_energy(self):
        """Get final energy after optimization (if available)."""
        if self.mol is None:
            return None

        try:
            props = AllChem.MMFFGetMoleculeProperties(self.mol)
            if props:
                ff = AllChem.MMFFGetMoleculeForceField(self.mol, props)
                return ff.CalcEnergy()
            else:
                ff = AllChem.UFFGetMoleculeForceField(self.mol)
                return ff.CalcEnergy()
        except:
            return None
