# Form implementation generated from reading ui file 'addElectrons.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_addParticlesDialog(object):
    def setupUi(self, addParticlesDialog):
        addParticlesDialog.setObjectName("addParticlesDialog")
        addParticlesDialog.resize(544, 298)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=addParticlesDialog)
        self.buttonBox.setGeometry(QtCore.QRect(190, 250, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox = QtWidgets.QGroupBox(parent=addParticlesDialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 521, 221))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 20, 521, 201))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.verticalLayoutWidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 517, 164))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.container = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents)
        self.container.setGeometry(QtCore.QRect(0, 0, 521, 201))
        self.container.setObjectName("container")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=self.container)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 501, 131))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addbutton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.addbutton.setObjectName("addbutton")
        self.horizontalLayout.addWidget(self.addbutton)
        self.removebutton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.removebutton.setObjectName("removebutton")
        self.horizontalLayout.addWidget(self.removebutton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(addParticlesDialog)
        self.buttonBox.accepted.connect(addParticlesDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(addParticlesDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(addParticlesDialog)

    def retranslateUi(self, addParticlesDialog):
        _translate = QtCore.QCoreApplication.translate
        addParticlesDialog.setWindowTitle(_translate("addParticlesDialog", "Dialog"))
        self.groupBox.setTitle(_translate("addParticlesDialog", "Add Particles"))
        self.addbutton.setText(_translate("addParticlesDialog", "Add"))
        self.removebutton.setText(_translate("addParticlesDialog", "Remove"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    addParticlesDialog = QtWidgets.QDialog()
    ui = Ui_addParticlesDialog()
    ui.setupUi(addParticlesDialog)
    addParticlesDialog.show()
    sys.exit(app.exec())
