# Form implementation generated from reading ui file 'UI/addElectrons.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_addParticlesDialog(object):
    def setupUi(self, addParticlesDialog):
        addParticlesDialog.setObjectName("addParticlesDialog")
        addParticlesDialog.resize(544, 298)
        addParticlesDialog.setSizeGripEnabled(True)
        self.dialogLayout = QtWidgets.QVBoxLayout(addParticlesDialog)
        self.dialogLayout.setContentsMargins(10, 10, 10, 10)
        self.dialogLayout.setObjectName("dialogLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=addParticlesDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 517, 164))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addbutton = QtWidgets.QPushButton(parent=self.groupBox)
        self.addbutton.setObjectName("addbutton")
        self.horizontalLayout.addWidget(self.addbutton)
        self.removebutton = QtWidgets.QPushButton(parent=self.groupBox)
        self.removebutton.setObjectName("removebutton")
        self.horizontalLayout.addWidget(self.removebutton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.dialogLayout.addWidget(self.groupBox)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=addParticlesDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.dialogLayout.addWidget(self.buttonBox)

        self.retranslateUi(addParticlesDialog)
        self.buttonBox.accepted.connect(addParticlesDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(addParticlesDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(addParticlesDialog)

    def retranslateUi(self, addParticlesDialog):
        _translate = QtCore.QCoreApplication.translate
        addParticlesDialog.setWindowTitle(_translate("addParticlesDialog", "Dialog"))
        self.groupBox.setTitle(_translate("addParticlesDialog", "Add Particles"))
        self.addbutton.setText(_translate("addParticlesDialog", "Add"))
        self.removebutton.setText(_translate("addParticlesDialog", "Remove"))
