# Form implementation generated from reading ui file 'geometry_visualizator.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(904, 752)
        self.editpanel_widget = QtWidgets.QWidget(parent=Form)
        self.editpanel_widget.setGeometry(QtCore.QRect(540, 10, 346, 731))
        self.editpanel_widget.setMinimumSize(QtCore.QSize(346, 0))
        self.editpanel_widget.setMaximumSize(QtCore.QSize(346, 16777215))
        self.editpanel_widget.setObjectName("editpanel_widget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.editpanel_widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(19, 19, 311, 701))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.moleculeinfo_groupbox = QtWidgets.QGroupBox(parent=self.verticalLayoutWidget)
        self.moleculeinfo_groupbox.setObjectName("moleculeinfo_groupbox")
        self.infotextbox = QtWidgets.QTextEdit(parent=self.moleculeinfo_groupbox)
        self.infotextbox.setGeometry(QtCore.QRect(0, 20, 311, 321))
        self.infotextbox.setReadOnly(True)
        self.infotextbox.setObjectName("infotextbox")
        self.verticalLayout.addWidget(self.moleculeinfo_groupbox)
        self.atoms_groupbox = QtWidgets.QGroupBox(parent=self.verticalLayoutWidget)
        self.atoms_groupbox.setObjectName("atoms_groupbox")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=self.atoms_groupbox)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 291, 251))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.addatombutton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        self.addatombutton.setObjectName("addatombutton")
        self.verticalLayout_2.addWidget(self.addatombutton)
        self.removeatoms = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        self.removeatoms.setObjectName("removeatoms")
        self.verticalLayout_2.addWidget(self.removeatoms)
        self.rotatebutton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        self.rotatebutton.setObjectName("rotatebutton")
        self.verticalLayout_2.addWidget(self.rotatebutton)
        self.optimizebutton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        self.optimizebutton.setObjectName("optimizebutton")
        self.verticalLayout_2.addWidget(self.optimizebutton)
        self.ok_cancel_buttonBox = QtWidgets.QDialogButtonBox(parent=self.atoms_groupbox)
        self.ok_cancel_buttonBox.setGeometry(QtCore.QRect(0, 320, 309, 25))
        self.ok_cancel_buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.ok_cancel_buttonBox.setObjectName("ok_cancel_buttonBox")
        self.verticalLayout.addWidget(self.atoms_groupbox)
        self.pyvista_widget = QtInteractor(parent=Form)
        self.pyvista_widget.setGeometry(QtCore.QRect(11, 11, 521, 729))
        self.pyvista_widget.setObjectName("pyvista_widget")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.moleculeinfo_groupbox.setTitle(_translate("Form", "Info"))
        self.atoms_groupbox.setTitle(_translate("Form", "Options"))
        self.addatombutton.setText(_translate("Form", "Add Atoms"))
        self.removeatoms.setText(_translate("Form", "Remove Atoms"))
        self.rotatebutton.setText(_translate("Form", "Rotate Geometry"))
        self.optimizebutton.setText(_translate("Form", "Optimize Geometry"))
from pyvistaqt import QtInteractor


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
